version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "Australia/Sydney"
  open-pull-requests-limit: 20
  target-branch: 3.x-develop
  reviewers:
  - pandaskii
