<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implement hook_form_FORM_ID_alter()
 */
function govcms_security_form_user_admin_settings_alter(&$form, FormStateInterface $form_state) {
  $form['admin_role']['#access'] = FALSE;
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function govcms_security_user_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->id() == 1 && !Settings::get('govcms_security_super_ui')) {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}
