version: '2.1'

orbs:
  tests: 'govcms/tests@4'

jobs:
  validate_composer:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: Validate Composer
          command: composer validate --no-check-all --no-plugins

  drupal_practices:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: Check Drupal Practices
          command: composer show -i -D --no-plugins

  build:
    docker:
      - image: govcmsdev/govcms:latest-php8.3-apache
    working_directory: /app
    steps:
      - run:
          name: Clean Working Directory
          command: find /app -mindepth 1 -delete
      - checkout
      - run:
          name: Install GovCMS distribution
          command: composer update --profile --prefer-dist --optimize-autoloader --no-scripts
      - run:
          name: List all packages within the GovCMS distribution
          command: composer show -i -D --no-plugins
      - run:
          name: List outdated packages within the GovCMS distribution
          command: composer outdated -D --no-plugins
      - persist_to_workspace:
          root: /app
          paths:
            - .

workflows:
  test:
    jobs:
      - validate_composer
      - drupal_practices
      - build:
          requires:
            - validate_composer
      - tests/basic:
          requires:
            - build
      - tests/phpunit:
          requires:
            - build
      - tests/cypress:
          requires:
            - build
