version: '2.1'

orbs:
  tests: 'govcms/tests@4'

jobs:
  validate_composer:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: Validate Composer
          command: composer validate --no-check-all --no-plugins

  drupal_practices:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run:
          name: Check Drupal Practices
          command: composer show -i -D --no-plugins

workflows:
  test:
    jobs:
      - validate_composer
      - drupal_practices
      - tests/build:
          requires:
            - validate_composer
      - tests/basic:
          requires:
            - tests/build
      - tests/phpunit:
          requires:
            - tests/build
      - tests/cypress:
          requires:
            - tests/build
