<?php

/**
 * @file
 * Store array of data which will be imported.
 */

/**
 * An array of image media assets.
 */
function govcms8_default_content_default_media_image() {
  return [
    'standard-page-image' => [
      'bundle' => 'image',
      'name' => 'Standard page image - example',
      'alt' => 'Standard page image',
      'file' => 'standard-page-image.png',
    ],
    'event-current-image' => [
      'bundle' => 'image',
      'name' => 'Event current image - example',
      'alt' => 'Event current image',
      'file' => 'event-current-image.png',
    ],
    'event-future-image' => [
      'bundle' => 'image',
      'name' => 'Event future image - example',
      'alt' => 'Event future image',
      'file' => 'event-future-image.png',
    ],
    'event-past-image' => [
      'bundle' => 'image',
      'name' => 'Event past image - example',
      'alt' => 'Event past image',
      'file' => 'event-past-image.png',
    ],
    'blog-article-image' => [
      'bundle' => 'image',
      'name' => 'Blog image - example',
      'alt' => 'Blog image',
      'file' => 'blog-article-image.png',
    ],
    'event-image' => [
      'bundle' => 'image',
      'name' => 'Event image - example',
      'alt' => 'Event image',
      'file' => 'event-image.png',
    ],
    'news-and-media-image' => [
      'bundle' => 'image',
      'name' => 'News and media image - example',
      'alt' => 'News and media image',
      'file' => 'news-and-media-image.png',
    ],
    'foi-image' => [
      'bundle' => 'image',
      'name' => 'FOI image - example',
      'alt' => 'FOI image',
      'file' => 'foi-image.png',
    ],
    'item-image-1' => [
      'bundle' => 'image',
      'name' => 'Item image 1 - example',
      'alt' => 'Item image 1',
      'file' => 'item-image-1.png',
    ],
    'item-image-2' => [
      'bundle' => 'image',
      'name' => 'Item image 2 - example',
      'alt' => 'Item image 2',
      'file' => 'item-image-2.png',
    ],
    'item-image-3' => [
      'bundle' => 'image',
      'name' => 'Item image 3 - example',
      'alt' => 'Item image 3',
      'file' => 'item-image-3.png',
    ],
    'presentation-demo' => [
      'bundle' => 'image',
      'name' => 'Presentation – demo',
      'alt' => 'Presentation',
      'file' => 'presentation.jpg',
    ],
    'featured-image' => [
      'bundle' => 'image',
      'name' => 'Featured image - example',
      'alt' => 'Featured image',
      'file' => 'featured-image.png',
    ],
    'supplier-featured' => [
      'bundle' => 'image',
      'name' => 'GovCMS Drupal Services Panel Supplier featured – demo',
      'alt' => 'GovCMS Drupal Services Panel Supplier',
      'file' => 'govcms-logo-for-suppliers.png',
    ],
    'header-demo' => [
      'bundle' => 'image',
      'name' => 'Header - demo',
      'alt' => 'Header',
      'file' => 'header.png',
    ],
    'supplier' => [
      'bundle' => 'image',
      'name' => 'GovCMS Drupal Services Panel Supplier – demo',
      'alt' => 'GovCMS Drupal Services Panel Supplier',
      'file' => 'govcms-dsp-suppliers-logo-square.jpg',
    ],
    'ask-me-about-govcms' => [
      'bundle' => 'image',
      'name' => 'Ask me about GovCMS - demo',
      'alt' => 'Ask me about GovCMS',
      'file' => 'askmeaboutgovcms.jpg',
    ],
    'australian-parliament-house' => [
      'bundle' => 'image',
      'name' => 'Australian Parliament House',
      'alt' => 'Australian Parliament House',
      'file' => 'parliamentbyallan.jpg',
    ],
    'treasury-building' => [
      'bundle' => 'image',
      'name' => 'Treasury Building',
      'alt' => 'A photo of Treasury Building in Barton Canberra',
      'file' => 'treasury.jpg',
    ],
    'dark-waves-background' => [
      'bundle' => 'image',
      'name' => 'Dark waves background',
      'alt' => 'Dark waves background',
      'file' => 'background-beach.jpg',
    ],
  ];
}
