<?php

/**
 * @file
 * Support for media assets in GovCMS.
 */

use Drupal\govcms_media\OverrideHelper as Override;
use Drupal\govcms_media\Plugin\media\Source\File;
use Drupal\govcms_media\Plugin\media\Source\Image;
use Drupal\govcms_media\Plugin\media\Source\AudioFile;
use Drupal\govcms_media\Plugin\media\Source\VideoFile;
use Drupal\govcms_media\Form\MediaForm;

/**
 * Implements hook_media_source_info_alter().
 */
function govcms_media_media_source_info_alter(array &$sources) {
  $sources['file']['input_match']['field_types'] = ['file'];
  Override::pluginClass($sources['file'], File::class);

  $sources['image']['input_match']['field_types'] = ['image'];
  Override::pluginClass($sources['image'], Image::class);

  $sources['audio_file']['input_match']['field_types'] = ['audio_file'];
  Override::pluginClass($sources['audio_file'], AudioFile::class);

  $sources['video_file']['input_match']['field_types'] = ['video_file'];
  Override::pluginClass($sources['video_file'], VideoFile::class);
}

/**
 * Implements hook_entity_type_alter().
 */
function govcms_media_entity_type_alter(array &$entity_types) {
  if (\Drupal::moduleHandler()->moduleExists('media')) {

    // Use our specialized entity form for adding and editing media assets in
    // order to support dynamic preview generation.
    Override::entityForm($entity_types['media'], MediaForm::class);
    Override::entityForm($entity_types['media'], MediaForm::class, 'edit');

  }
}
