ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/php:7.4-cli-drupal

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY --from=cli /app /app

COPY tests /app/tests

COPY .docker/scripts/behat .docker/scripts/lint-theme /usr/bin/

RUN mkdir -p /app/tests/behat/screenshots \
  && echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/memory.ini \
  && composer install -d /app/tests -n --ansi --prefer-dist --no-suggest \
  && rm -rf /usr/local/etc/php/conf.d/memory.ini \
  && chmod +x /usr/bin/behat \
  && chmod +x /usr/bin/lint-theme
