#+TITLE: Security.txt Module README
#+AUTHOR: Daniel J. R. May
#+BEGIN_COMMENT
This is an emacs org-mode text file. You can convert it to a
pretty-printed text file called README.txt when in org-mode by
issuing the command: C-c C-e t u
#+END_COMMENT

* Introduction
The Security.txt module provides an implementation of the security.txt
draft RFC standard. Its purpose is to provide a standardised way to
document your website’s security contact details and policy. This
allows users and security researchers to securely disclose security
vulnerabilities to you.

* Installation
This module should be installed in the usual way. Read about
[[https://www.drupal.org/docs/extending-drupal/installing-modules][installing modules]].

* Configuration
Once you have installed this module you will want to perform the
following configuration.

** Permissions
You control the permissions granted to each role at
~/admin/people/permissions~. You will almost certainly want to give
everyone the ~View security.txt~ permission, i.e. give it to both the
~Anonymous User~ and ~Authenticated User~ roles.

You will only want to give the ~Administer security.txt~ permission to
very trusted roles.

** Security.txt configuration
The Security.txt configuration page can be found under ~System~ on the
Drupal configuration page. Fill in all the details you want to add to
your ~security.txt~ file, then press the ~Save configuration~ button.
You should then proceed to the ~Sign~ tab of the configuration form.

** Security.txt signing
You can provide a digital signature for your ~security.txt~ file by
following the instructions on the ~Sign~ tab of the module’s
configuration page.

* Use
Once you have completed the configuration of the Security.txt module
your security.txt and security.txt.sig files will be available at the
following standard URLs:

- /.well-known/security.txt
- /.well-known/security.txt.sig

* Further reading
- Learn more about the [[https://securitytxt.org/][security.txt standard]]
- Read the [[https://tools.ietf.org/html/draft-foudil-securitytxt-02][draft RFC]] 
